import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";
import { getThemeFromCookie } from "@/lib/theme";
import { buildPersonJsonLd } from "@/lib/seo/structured-data";
import { ThemeProvider } from "@/components/layout/ThemeProvider";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import "./globals.css";

/**
 * Root layout — Integration Blueprint 4.4, 8.2.
 *
 * This file handles exactly three things:
 *   1. Font loading (self-hosted, zero render-blocking external requests)
 *   2. Theme initialisation (server-side cookie read → data-theme on <html>)
 *   3. Structural composition: ThemeProvider → Navbar → main → Footer
 *
 * ThemeProvider wraps the whole tree so every client component anywhere
 * in the app can call useTheme() without prop-drilling.
 *
 * Font loading via next/font/local (Visual Design Spec 0.3, Implementation
 * Blueprint 8.2): each loader exposes a CSS variable that matches the
 * --font-* names already declared in globals.css's @theme block. The
 * className on <html> injects those variables into the document root so
 * Tailwind's font-display/font-body/font-mono utilities resolve correctly.
 *
 * NOTE: Font .woff2 files must exist in /public/fonts/ before this
 * builds successfully. Filenames match exactly what's referenced in the
 * src arrays below. If fonts haven't been added yet, comment out the
 * localFont calls and replace the className with empty string temporarily.
 */

const spaceGrotesk = localFont({
  src: [
    { path: "../public/fonts/space-grotesk-medium.woff2",  weight: "500", style: "normal" },
    { path: "../public/fonts/space-grotesk-semibold.woff2", weight: "600", style: "normal" },
  ],
  variable: "--font-display",
  display: "swap",
  preload: true,
  fallback: ["ui-sans-serif", "system-ui", "sans-serif"],
});

const inter = localFont({
  src: [
    { path: "../public/fonts/inter-regular.woff2",  weight: "400", style: "normal" },
    { path: "../public/fonts/inter-medium.woff2",   weight: "500", style: "normal" },
    { path: "../public/fonts/inter-semibold.woff2", weight: "600", style: "normal" },
  ],
  variable: "--font-body",
  display: "swap",
  preload: true,
  fallback: ["ui-sans-serif", "system-ui", "sans-serif"],
});

const jetbrainsMono = localFont({
  src: [
    { path: "../public/fonts/jetbrains-mono-medium.woff2", weight: "500", style: "normal" },
  ],
  variable: "--font-mono",
  display: "swap",
  preload: false, // mono is used at small sizes in tags/metadata; not LCP-critical
  fallback: ["ui-monospace", "SF Mono", "monospace"],
});

// Root-level metadata export — acts as the site-wide fallback in the
// unlikely event a page forgets to call buildMetadata(). Per-page
// metadata is generated by lib/seo/metadata.ts helpers.
export const metadata: Metadata = {
  title: {
    default: "Portfolio",
    template: "%s — Portfolio",
  },
  description: "building systems that turn curiosity into shipped work.",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Read the theme cookie server-side — this prevents the dark→light
  // flash that localStorage-only theme implementations produce.
  // getThemeFromCookie() is a server action in lib/theme.ts.
  const theme = await getThemeFromCookie();

  const fontVars = [
    spaceGrotesk.variable,
    inter.variable,
    jetbrainsMono.variable,
  ].join(" ");

  return (
    <html
      lang="en"
      data-theme={theme}
      className={fontVars}
      // Suppress the hydration warning that would otherwise fire because
      // data-theme may differ between the server (cookie value) and the
      // client's first render in environments where the cookie isn't sent
      // (e.g. a fresh Incognito window). The ThemeProvider reconciles on
      // mount by checking prefers-color-scheme.
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider initialTheme={theme}>
          {/* Skip-navigation is rendered inside Navbar (Component Library A1) */}
          <Navbar />

          {/* id="main-content" is the skip-nav target */}
          <main id="main-content">
            {children}
          </main>

          <Footer />
        </ThemeProvider>

        {/* Person JSON-LD — site-wide structured data (Implementation Blueprint 7.5).
            Placed here so it appears on every page without each page needing
            to import and render it individually. */}
        <Script
          id="person-jsonld"
          type="application/ld+json"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(buildPersonJsonLd()),
          }}
        />
      </body>
    </html>
  );
}
